apiVersion: v1
kind: ConfigMap
metadata:
  name: push-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s

    scrape_configs:
      - job_name: 'surplus-food-app'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['backend-service.default.svc.cluster.local:5000']

    remote_write:
      - url: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom
        basic_auth:
          username: "${GF_USERNAME}"
          password: "${GF_API_KEY}"
