apiVersion: v1
kind: Secret
metadata:
  name: grafana-creds
type: Opaque
data:
  username: ${{ secrets.GRAFANA_USERNAME_BASE64 }}  # echo -n "2546765" | base64
  api-key: ${{ secrets.GRAFANA_API_KEY_BASE64 }}     # echo -n "glc_ey..." | base64
