name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/project-bolt

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest

    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Notify via AWS Lambda
      run: |
        curl -X POST "$LAMBDA_FUNCTION_URL" \
        -H "Content-Type: application/json" \
        -d '{
          "message": "✅ Docker image pushed to DockerHub: '${{ env.IMAGE_NAME }}:latest' and deployed to Kubernetes"
        }'
      env:
        LAMBDA_FUNCTION_URL: ${{ secrets.LAMBDA_FUNCTION_URL }}

    - name: Create dashboards folder
      run: mkdir -p dashboards

    - name: Download Grafana dashboards
      run: bash download-dashboards.sh

    - name: Commit downloaded dashboards to repo
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add dashboards/
        git commit -m "⬇️ Auto-update Grafana dashboards"
        git push || echo "Nothing to commit"
