name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Or your desired branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up KUBECONFIG for local K3s
        run: |
          mkdir -p ~/.kube
          sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
          sudo sed -i 's/127.0.0.1/172.31.91.131/' ~/.kube/config
          sudo chown $USER:$USER ~/.kube/config

      - name: Verify kubectl context
        run: kubectl config get-contexts

      - name: Show nodes (optional)
        run: kubectl get nodes

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/ --validate=false
